### PR TITLE
tools: improve nix caching

### PR DESCRIPTION
**Pull request by akacase**
See #96 -- introduce `developPackage`, compat layer for `shell.nix` and some formatting. This fixes nix build/cache issues.
---

## hsec-tools

- [x] Previous advisories are still valid

### CODE REVIEW

**Comment by akacase** [comment]
@blackheaven I'll let you add the docker image, we'll need to sync up on #80 -- please let me know if you need any help.

**Review by TristanCacqueray — APPROVED** [review]
The build took 3m16s, thanks!

**Comment by frasertweedale** [comment]
I'll leave it to the nix users to review and merge, but this looks very promising!

**Comment by akacase** [comment]
Merging.

**Pull request merged**
