### PR TITLE
Add GHSA-xj5q-fv23-575g for pandoc

### PR DESCRIPTION
**Pull request by darakian**
Hey all, was going through some advisories I've been tracking and noticed you were missing one that I had. Hope I followed the format correctly for adding an advisory

Source report:
https://github.com/jgm/pandoc/security/advisories/GHSA-xj5q-fv23-575g

---

## Advisory

- [x] It's not duplicated
- [x] All fields are filled
- [ ] It is validated by `hsec-tools`

## hsec-tools

- [ ] Previous advisories are still valid

### CODE REVIEW

**Review by TristanCacqueray — APPROVED** [review]
Thanks!

**Comment by darakian** [comment]
> Thanks!

Happy to help 😄 
Side note; we also have a repo level api for ghsa's should you want to monitor specific orgs/repos 😉 
https://docs.github.com/en/rest/security-advisories/repository-advisories?apiVersion=2022-11-28

**Comment by TristanCacqueray** [comment]
@blackheaven do you know why the CI is failing on the Fetch task?

**Comment by blackheaven** [comment]
The cache expired, we might recompute either periodically, or on demand, I'll handle it later

**Review by blackheaven — APPROVED** [review]

**Comment by blackheaven** [comment]
Here we are, thanks for your contribution!

**Pull request merged**
