### PR TITLE
`cabal-audit`: init

### PR DESCRIPTION
**Pull request by MangoIV**
### usage 

```console
λ nix run github:mangoiv/security-advisories/mangoiv/cabal-audit-osv#cabal-audit --
trying to clone https://github.com/haskell/security-advisories
Cloning into '/tmp/cabal-audit-726d3e9345b766bc'...
remote: Enumerating objects: 172, done.
remote: Counting objects: 100% (172/172), done.
remote: Compressing objects: 100% (129/129), done.
remote: Total 172 (delta 6), reused 114 (delta 1), pack-reused 0
Receiving objects: 100% (172/172), 116.55 KiB | 1.31 MiB/s, done.
Resolving deltas: 100% (6/6), done.


Found advisories:

dependency "base" at version 4.18.1.0 is vulnerable for:
  HSEC-2023-0007 "readFloat: memory exhaustion with large exponent"
  published: 2024-04-23 12:43:30 +1000
  https://haskell.github.io/security-advisories/advisory/HSEC-2023-0007
  No fix version available
  toml, parser, dos

dependency "process" at version 1.6.17.0 is vulnerable for:
  HSEC-2024-0003 "process: command injection via argument list on Windows"
  published: 2024-04-23 12:43:30 +1000
  https://haskell.github.io/security-advisories/advisory/HSEC-2024-0003
  Fix available since version 1.6.19.0
  windows
```

> [!Note]
> if this causes some error wrt a lock file incompatibility, upgrade your nix version ;)

### features implemented 

- query the repository for vulnerabilities 
- provide local repository 
- pretty output 
- run the cabal solver on a project and match vulnerabilities against that 
- propose fix version
- link to security-advisories website 
- playtest

### open features 

- don't only provide the latest fix version but a range of fix versions
- check for the newest package on hackage that is greater than the fix version
- more configuration configure the output 
- json output instead of only pretty stdout 
- use API instead of repository
- more solver options (perhaps offer a special flags to pass on options to cabal)
- more structured monadic code (it's all IO for simplicity)

## other changes 

- gave the nix code a polish 
- gave the devshell a polish 
- introduced pre-commit-hooks.nix (please tell me if that's not wanted)

### CODE REVIEW

**Comment by blackheaven** [comment]
It looks great, thanks for the contribution!

**Comment by MangoIV** [comment]
I have not done anything yet 😅

**Comment by MangoIV** [comment]
I need to check what's wrong with `nixpkgs`; it reports that it installs multiple versions of `Cabal-Syntax` when building `hsec-cabal` with `nix`, this is probably due to it being a boot library.

**Comment by MangoIV** [comment]
image

mvp seems to work (project with vulnerable library spits it out :3

**Comment by MangoIV** [comment]
I wonder if I can get rid of cabal-install s own command line parser. It’s awful. So noisy

**Comment by jappeace** [comment]
good work fruity fren

**Comment by MangoIV** [comment]
note to self: `xh GET https://hackage.haskell.org/package/network/preferred Accept:application/json` find newest, not vulnerable version; if any; do we propose versions that are older than the current version?

**Comment by frasertweedale** [comment]
> note to self: `xh GET https://hackage.haskell.org/package/:package/preferred Accept:application/json` find newest, not vulnerable version; if any; do we propose versions that are older than the current version?

That is a very good question.  I would say it's fine to propose an older version, if and only if it satisfies the solver.

**Comment by MangoIV** [comment]
image

**Comment by MangoIV** [comment]
calling without arguments: 
image

**Comment by MangoIV** [comment]
calling with local path: 
image

**Comment by MangoIV** [comment]
calling in a directory with no known vulnerabilities
image

**Comment by MangoIV** [comment]
I have no idea why the docker build is failing

**Comment by blackheaven** [comment]
I had a fight with GitHub Actions on Saturday, try to rebase your branch, I hope it'll be fine

**Comment by MangoIV** [comment]
hmmm https://haskell.github.io/security-advisories/advisory/HSEC-2023-0007.html do I understand correctly, that theoretically, *all* packages should spit out a warning about `base`?

**Comment by MangoIV** [comment]
oh, also I can't do on github directly, but may I kindly ask for a review 
@frasertweedale @blackheaven ?

**Comment by blackheaven** [comment]
> @blackheaven I recently merged; I don't think this branch lack behind `main` at all?

I have merged right after my comment, sorry for that.

GitHub UI says this PR has conflicts, maybe fixing them would be enough.

> hmmm https://haskell.github.io/security-advisories/advisory/HSEC-2023-0007.html do I understand correctly, that theoretically, _all_ packages should spit out a warning about `base`?

Currently, yes, we know it's terrible.



> oh, also I can't do on github directly, but may I kindly ask for a review

I'll have a look later today.

**Comment by MangoIV** [comment]
we need a way to distribute this other than nix; perhaps creating another docker container might work but that has equal tradeoffs; best would be to release a statically linked executable (that is what nix spits out anyways, so shouldn't be hard to, in future, just provide  this as a downloads)

**Comment by ulidtko** [comment]
> we need a way to distribute this other than nix

hey, what about `cabal install cabal-audit` ? @MangoIV 

... https://hackage.haskell.org/package/cabal-audit oh OMG, now what's this :see_no_evil:

**Comment by MangoIV** [comment]
it's some ancient package https://github.com/pikajude/cabal-audit

**Comment by ulidtko** [comment]
@MangoIV no, horrible... Just imagine the UX. A random dude:
* learns `cabal audit` is a thing
* `cabal install cabal-audit`
* ...
* `Error: cabal: Could not resolve dependencies:`

I mean. A caveat like that, right at installation time (before we even tried the tool yet) — is a turn down. Not a good sign

**Comment by ulidtko** [comment]
JFYI, if the author is unresponsive, [there's a procedure][1] to claim the name on hackage

[1]: https://wiki.haskell.org/Taking_over_a_package

**Comment by MangoIV** [comment]
this seems to be intended for updating/ maintaining packages, not reclaiming the namespace; I will have to ask first if that's legal anyways...

**Comment by MangoIV** [comment]
Apparently it is! You bump the epoch number (that’s the first number in PVP) and that’s it! Easy

**Comment by MangoIV** [comment]
I have sent out a mail to joel

**Comment by MangoIV** [comment]
i got an answer from joel, he's willing to hand over the namespace :heart:

**Review by Kleidukos — COMMENTED** [review]
lgtm

**Comment by MangoIV** [comment]
Thanks Hecate ❤️

**Review by blackheaven — APPROVED** [review]

**Comment by blackheaven** [comment]
A last rebase and we should be good to go

**Comment by MangoIV** [comment]
I’ll tell you when I’m ready

**Comment by MangoIV** [comment]
will do one more iteration of cleanup and then should be good. I wanted to add an integration test but that depends on the issue I just opened.

**Review by blackheaven — APPROVED** [review]

**Comment by MangoIV** [comment]
I think this is gtg now, feel free to review; I wanted to add some tests but they seem to depend on the `.git` directory and I have yet to figure out how to test this properly within `nix`...

**Review by blackheaven — APPROVED** [review]

**Review by blackheaven — APPROVED** [review]

**Comment by MangoIV** [comment]
I have some follow up plans, should we merge this first or should I push here?

**Comment by frasertweedale** [comment]
@MangoIV a side note: in the SRT quarterly status report I want to give you kudos for your contributions.  Shall I refer to you by "MangoIV", or by some other name?

**Comment by MangoIV** [comment]
MangoIV is good 😅

**Comment by MangoIV** [comment]
:pleading_face: :point_right: :point_left:

**Comment by MangoIV** [comment]
Hi! can I do something to make this move forward?

**Comment by MangoIV** [comment]
Hi! Little bump on this; what can I do to make this move forward? Mind, I also have an email by Joel where he intents to hand over the hackage namespace for `cabal-audit`, is there any news on how this is going to be handled?

**Comment by MangoIV** [comment]
Hi @pwm, this is because there's an incompatibility between nix versions wrt flake lock files, (to be fair, they *do* coin it as an experimental feature); you can fix it by upgrading your nix version to something *somewhat* recent. 

Also be sure to try out the newest version which includes a couple more fixes and allows to output a semi-structured format; 

```bash
nix run github:mangoiv/security-advisories/mangoiv/cabal-audit-osv#cabal-audit --
```

Thank you for beta-testing!

**Comment by MangoIV** [comment]
This PR was rejected because it is currently out of scope for the security-avisories team. Please find the work at github.com/mangoiv/cabal-audit

**Comment by pwm** [comment]
@MangoIV do you know where we can read more on what is in-scope vs. out of scope? From an end user perspective a security advisory db in itself is not that useful, it needs tooling like `cabal-audit` to make it useful.

**Comment by MangoIV** [comment]
@pwm This is not something I can answer. As far as I am aware this tool was part of the "future goals" of the working group when it was founded. Perhaps open an issue on this repo?

**Comment by blackheaven** [comment]
> @MangoIV do you know where we can read more on what is in-scope vs. out of scope? From an end user perspective a security advisory db in itself is not that useful, it needs tooling like `cabal-audit` to make it useful.

We should have a dedicated page but we stated it in our [last report](https://discourse.haskell.org/t/haskell-security-response-team-2024-january-march-report/9285):

> The Haskell Security Response Team (SRT) is a volunteer organisation within the Haskell Foundation that is building tools and processes to aid the entire Haskell ecosystem in assessing and responding to security risks. In particular, we maintain a [database](https://github.com/haskell/security-advisories) of security advisories that can serve as a data source for security tooling.

**Pull request closed without merging**
