### PR TITLE
fix(tool): speedup nix build time WIP

### PR DESCRIPTION
**Pull request by blackheaven**
---

## hsec-tools

- [x] Previous advisories are still valid

### CODE REVIEW

**Comment by frasertweedale** [comment]
I'll leave this for the nix folks to review, lest I merge it too early like last time :]

**Comment by akacase** [comment]
@blackheaven https://determinate.systems/posts/magic-nix-cache -- :)

**Comment by blackheaven** [comment]
@akacase Thanks, I hope it won't be too big.

However I think we need to use a cachix, @david-christiansen does HF provide one for haskell projects?

**Comment by david-christiansen** [comment]
The HF does not provide that service. What is it? What is the value? What would it cost?

**Comment by TristanCacqueray** [comment]
@david-christiansen it's a service to cache ci nix build (e.g. the build-depends), and the value is to greatly improve ci run time. There is a free tier for OSS projects, but the quota is bound to a single user or org.

@blackheaven perhaps we could try (announced today) https://determinate.systems/posts/magic-nix-cache ?

**Comment by blackheaven** [comment]
@TristanCacqueray @akacase just suggested it

I just tested it, we go from 42m to 30m, not a real improvement IMO.

I think the only viable option would be to setup cachix, but I don't feel like pushing for it as it's not currently setup and I guess agreeing on the tooling at HF-level is out of the scope of this PR.

**Comment by david-christiansen** [comment]
If it's a matter of paying an affordable monthly subscription, then HF can definitely provide it. We don't need to agree to use something for every project - it's fine if it's useful for one.

I don't want to be administering any servers, though - better to pay a bit of money and have something that just works.

**Comment by blackheaven** [comment]
Sure, but I don't think we are making an intense use of nix (for the moment :crossed_fingers:), let's reevaluate this in few weeks.

**Pull request closed without merging**
