### PR TITLE
feat(ci): generate and publish advisories website

### PR DESCRIPTION
**Pull request by blackheaven**

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]

**Review by TristanCacqueray — APPROVED** [review]

**Comment by TristanCacqueray** [comment]
The job worked and we now have a gh-pages branch, though the website doesn't seem to be available yet. Should it be at https://haskell.github.io/security-advisories/ ?

**Comment by frasertweedale** [comment]
@TristanCacqueray it's because the branch name is `generated/gh-pages`, not `gh-pages`.

**Comment by blackheaven** [comment]
It's weird because it seems to be correctly configured, I'll dig into it.

**Comment by blackheaven** [comment]
It's may be due to the fact we don't have a haskell.github.io

**Comment by frasertweedale** [comment]
@blackheaven it is the `gh-pages` branch that gets published.  We are pushing to `generated/gh-pages`.

**Comment by blackheaven** [comment]
Not necessarily, it's configured here https://github.com/haskell/security-advisories/settings/pages

**Comment by frasertweedale** [comment]
Ah right... I had no idea it was configurable!  Thanks for the
clarification.

**Pull request merged**
